# Generated by Django 6.0.6 on 2026-06-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_refeicao_opcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospaciente',
            name='colesterol_hdl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='colesterol_ldl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='colesterol_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='trigliceridios',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='idade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='carboidratos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='gorduras',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='proteinas',
            field=models.FloatField(),
        ),
    ]
