# Generated by Django 6.0.6 on 2026-06-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_dadospaciente_colesterol_hdl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='idade',
            field=models.IntegerField(max_length=100),
        ),
    ]
